### ISSUE TITLE
Product scoped per store

### ISSUE THREAD

**Issue by adrien2p** [shahednasser/medusa-marketplace-tutorial#1]
https://github.com/shahednasser/medusa-marketplace-tutorial/blob/8ac26303ed2bb602c90fcc898e4bf9985340f470/src/modules/product/services/product.service.ts#L43

you should not be able to create a product that does not belongs to a store, it should be mandatory. What would be the use case where it is not mandatory for a marketplace ?

**Comment by shahednasser** [comment]
Good point! I'll make that change
