### ISSUE TITLE
 How to add new route with other path than /admin or /store

### ISSUE THREAD

**Issue by AbdallahRahal** [shahednasser/medusa-marketplace-tutorial#10]
Hi, I'm using medusa to build a marketplace and I need to create route with new path.
 
I know it is possible to override existing path (like admin/create-user) or create route from existing path (like admin/newRandomRoute), but I want to create a new route from scratch (like newRandomRoute/).

I created a new module 'Test' with a router
`

    @Router({ routes: [
        // WORK
        {
            requiredAuth: false,
            path: '/admin/test',
            method: 'get',
            handlers: [wrapHandler(test)],
        },

        // DOESNT WORK
        {
            requiredAuth: false,
            path: '/test/test',
            method: 'get',
            handlers: [wrapHandler(test)],
        },
        {
            requiredAuth: false,
            path: '/test',
            method: 'get',
            handlers: [wrapHandler(test)],
        },
    ],})

`

I dont know how to make  '/test/test' or '/test' path (or any other path that doesn't start with admin or store) work.

Could you help me please ?

**Comment by shahednasser** [comment]
This by default should work in Medusa, however, I'm not sure about the details related to the extender. @adrien2p wdyt?

**Comment by adrien2p** [comment]
@AbdallahRahal hi, it is not possible at the moment, you can do that with medusa but i did not allowed it yet into the extender since it was not a need and all routes where going either behind admin or store path.
