### ISSUE TITLE
Created Users/Products don't have "store_id"

### ISSUE THREAD

**Issue by SullyvanBoulanger** [shahednasser/medusa-marketplace-tutorial#16]
Hello :)

I started the tutorial via [this link](https://medusajs.com/blog/medusa-extender/) and arrived at the moment of the login, the user object returned don't possess a "store_id" attribute. I can create users with path "/admin/users" when I'm logged in admin. Same for products but "store_id" don't exist in objects returned.

I followed it without making any modifications. So I cloned this project in order to see differences and copy paste file to test but nothing change.

I tried to run the project and I have an error : 

```bash
Initializing databaseError: getaddrinfo EAI_AGAIN undefined
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'undefined'
}
```

Can you help please ? 
Since I'm a beginner in Medusa and Medusa Extender, I don't know if it's something I don't make properly or other

PS : I've also read [this tutorial](https://dev.to/medusajs/create-an-open-source-commerce-marketplace-part-1-3m5k) but it's the same

**Comment by shahednasser** [comment]
Hi @SullyvanBoulanger. It seems like you didn't configure your database correctly.  Can you share with me your configuration in `medusa-config.js` (make sure to remove any passwords you've saved there and replace them with a placeholder or something else).

**Comment by SullyvanBoulanger** [comment]
I don't have modify this file at all

This is how it looks in my project following the tutorial : 

```js
// CORS when consuming Medusa from admin
const ADMIN_CORS = process.env.ADMIN_CORS || "http://localhost:7000,http://localhost:7001";

// CORS to avoid issues when consuming Medusa from a client
const STORE_CORS = process.env.STORE_CORS || "http://localhost:8000";

// Database URL (here we use a local database called medusa-development)
const DATABASE_URL =
  process.env.DATABASE_URL || "postgres://localhost/medusa-store";

// Medusa uses Redis, so this needs configuration as well
const REDIS_URL = process.env.REDIS_URL || "redis://localhost:6379";

// Stripe keys
const STRIPE_API_KEY = process.env.STRIPE_API_KEY || "";
const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET || "";

// This is the place to include plugins. See API documentation for a thorough guide on plugins.
const plugins = [
  `medusa-fulfillment-manual`,
  `medusa-payment-manual`,
  // Uncomment to add Stripe support.
  // You can create a Stripe account via: https://stripe.com
  // {
  //   resolve: `medusa-payment-stripe`,
  //   options: {
  //     api_key: STRIPE_API_KEY,
  //     webhook_secret: STRIPE_WEBHOOK_SECRET,
  //   },
  // },
];

module.exports = {
  projectConfig: {
    // redis_url: REDIS_URL,
    // For more production-like environment install PostgresQL
    // database_url: DATABASE_URL,
    // database_type: "postgres",
    database_database: "./medusa-db.sql",
    database_type: "sqlite",
    store_cors: STORE_CORS,
    admin_cors: ADMIN_CORS,
  },
  plugins,
};
```

**Comment by SullyvanBoulanger** [comment]
Thanks a lot for your answer :)

I was able to configure a database and migrate the seed in it.
But, I have the same problem with "store_id", it's not present for users or products \^\^'

**Comment by SullyvanBoulanger** [comment]
Yes but I checked users and products by a GET request on path /admin/products or by creating an user and look the returned object

`npm run build` works but `medex m --run` has an error which tell there is duplicated migrations for addStoreIdToProduct and addStoreIdToUser :

```shell
Error: Duplicate migrations: addStoreIdToProduct1645034402086, addStoreIdToUser1611063162649
```

**Comment by shahednasser** [comment]
So that means that the columsn are available in the database but they're not being returned in the endpoint right?

If you followed along with the tutorial completely, specifically by adding the `retieve` method in the `UserService`, you should see the `store_id` in the returned user. As explained in the article:

> This new class overrides the retrieve method to ensure that the user returned is the new User entity class you created earlier.

However, this is not done for the product in the tutorial. You'll need to also override the method `https://docs.medusajs.com/references/services/classes/ProductService#retrieve` for that to work similarly to how it's done in the `UserService`.

Let me know if this resolves your issue.

**Comment by shahednasser** [comment]
Ok I have rechecked this issue and it seems like this is caused by a new update in the extender. Now, the migration files must be at root level of the module. So, for example, `src/modules/user/migrations/user.migration.ts` should be in `src/modules/user/user.migration.ts` instead.

Can you try moving the migrations for products as well, then run the build and migrate command I mentioned earlier?

**Comment by SullyvanBoulanger** [comment]
After moving migrations files in root, migration works ! :)

For the columns, I didn't check the database and don't know how to access it sorry.
But in the endpoint, there isn't these columns and it's the same after the migration :/

**Comment by shahednasser** [comment]
If the migrations worked then the columns should be added. Does the user object in the login endpoint show a store_id?

**Comment by shahednasser** [comment]
What was the output when you ran the migration?

**Comment by SullyvanBoulanger** [comment]
Sorry, I don't have it anymore \^\^'

But I had a message which said that the migration success

**Comment by shahednasser** [comment]
I would suggest removing your database and follow the new instructions [here](https://github.com/shahednasser/medusa-marketplace-tutorial#seed-and-migrate-database). You can also clone the [part-1](https://github.com/shahednasser/medusa-marketplace-tutorial/tree/part-1) branch to make sure you have the correct code in case you missed any step in the tutorial.

**Comment by SullyvanBoulanger** [comment]
I'm still trying to make it works but I found an another issue when I cloned part-1

In modules/product/services/product.service.ts, ConstructorParams type isn't correct and throw an error
To fix it, I added 2 members : 

```ts
type ConstructorParams = {
  manager: any;
  loggedInUser: User;
  productRepository: any;
  productVariantRepository: any;
  productOptionRepository: any;
  eventBusService: any;
  productVariantService: any;
  productCollectionService: any;
  productTypeRepository: any;
  productTagRepository: any;
  imageRepository: any;
  searchService: any;
  userService: UserService;
  cartRepository: any; //added
  priceSelectionStrategy: any; //added
};
```
Idk if any is good for placeholder type btw

**Comment by shahednasser** [comment]
Thanks for reporting this. This is because part-1 was created before the new updated in Medusa which added those 2 dependencies. I'll make sure to fix it to include them.

**Comment by shahednasser** [comment]
I just tried reproducing this by cloning part 1, installing the dependencies and following the steps detailed in the readme. I can see `store_id` in the user object in endpoints.

I can't seem to run into the same issue. Maybe if you can detail for me the exact steps you're taking we can find the problem

**Comment by SullyvanBoulanger** [comment]
I tried 2 ways : 

First by cloning the project. I clone it with 
```shell
git clone -b part-1 https://github.com/shahednasser/medusa-marketplace-tutorial#seed-and-migrate-database
```
Then I install dependencies with `npm i` and execute `npm run seed` after configuring a database in .env and medusa-config.js
And I have an error for express : 
```shell
Initializing expressexpress-session deprecated req.secret; provide secret option node_modules/@medusajs/medusa/dist/loaders/express.js:82:51
TypeError: JwtStrategy requires a secret or key
    at new JwtStrategy (/home/sullyvan/Documents/Tests/Medusa/medusa-marketplace-tutorial/node_modules/passport-jwt/lib/strategy.js:45:15)
    at /home/sullyvan/Documents/Tests/Medusa/medusa-marketplace-tutorial/node_modules/@medusajs/medusa/dist/loaders/passport.js:78:36
    at step (/home/sullyvan/Documents/Tests/Medusa/medusa-marketplace-tutorial/node_modules/@medusajs/medusa/dist/loaders/passport.js:33:23)
    at Object.next (/home/sullyvan/Documents/Tests/Medusa/medusa-marketplace-tutorial/node_modules/@medusajs/medusa/dist/loaders/passport.js:14:53)
    at /home/sullyvan/Documents/Tests/Medusa/medusa-marketplace-tutorial/node_modules/@medusajs/medusa/dist/loaders/passport.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/sullyvan/Documents/Tests/Medusa/medusa-marketplace-tutorial/node_modules/@medusajs/medusa/dist/loaders/passport.js:4:12)
    at /home/sullyvan/Documents/Tests/Medusa/medusa-marketplace-tutorial/node_modules/@medusajs/medusa/dist/loaders/passport.js:49:12
    at /home/sullyvan/Documents/Tests/Medusa/medusa-marketplace-tutorial/node_modules/@medusajs/medusa/dist/loaders/index.js:182:65
    at step (/home/sullyvan/Documents/Tests/Medusa/medusa-marketplace-tutorial/node_modules/@medusajs/medusa/dist/loaders/index.js:52:23)
    at Object.next (/home/sullyvan/Documents/Tests/Medusa/medusa-marketplace-tutorial/node_modules/@medusajs/medusa/dist/loaders/index.js:33:53)
    at fulfilled (/home/sullyvan/Documents/Tests/Medusa/medusa-marketplace-tutorial/node_modules/@medusajs/medusa/dist/loaders/index.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
⠧ Initializing express
```
Can't find a way to avoid this error

Second way by creating a fresh new medusa project. I add to it Medusa Extender (`medex init` + `npm i medusa-extender`)
I configure the file medusa-config.js to link a database. Then, I add in modules repositories `product`, `user` and `store` and fix the ControllerParam type btw. Those repositories come from the marketplace tutorial project which was cloned earlier

In maint.ts, I add modules in the load. Then I exec `npm run build`, `npm run seed` and `medex m --run` in this respectively order.

I start the server with `medusa develop` and do some request on `postman` : 

```js
// POST Request
// /admin/auth

{
  "email": "admin@medusa-test.com",
  "password": "supersecret"
}
```

```js 
// POST Request
// /admin/users

{
  "email": "example@gmail.com",
  "password": "supersecret"
}
```

```js
// GET Request
// /admin/products
```

**Comment by SullyvanBoulanger** [comment]
I don't have the previous issue now

I can run `npm run seed`, it success and can see . Then `medex m --run` outputs : 
```shell
No migrations are pending
Migration command: 41.768ms
```
And start the server and don't have "store_id" :'(

**Comment by shahednasser** [comment]
did you run the build command before the migrate commands

**Comment by SullyvanBoulanger** [comment]
No, I followed precisely the commands on the README.md \^\^'

I run it and after that `medex m --run`, start the server and it's the same result as always, no "store_id"

**Comment by shahednasser** [comment]
unfortunately I don't know what the issue could be. I've tested it and it works fine.

Can you try using the `part-2` branch or master branch? Maybe that will work.

**Comment by SullyvanBoulanger** [comment]
After some researches, in the database, I have the store_id in the table `product` where there are all the products.
But this column is empty for every product, even if I create a new one

And I don't find users in the database, I have a table named user but it possess columns like returned object when login
I will try using the `part-2`

Sorry for the bothering btw \^\^'

**Comment by shahednasser** [comment]
Make sure that when you are creating the product you are a user that has a store. So basically you can follow this flow:

1. Login with the demo admin (email: admin@medusa-test.com password: supersecret)
2. Create new user -> this will create a store for the new user
3. Login with new user
4. Create product
5. Fetch products

Let me know if this works.

**Comment by SullyvanBoulanger** [comment]
1. Login with the demo admin => no problem
2. Create new user -x> The user is created but don't possess a store_id, this is the output : 
```json
{
    "user": {
        "email": "example@gmail.com",
        "id": "usr_01G5KWCKW6KDRS4BPRPH1YRRQD",
        "role": "member",
        "first_name": null,
        "last_name": null,
        "api_token": null,
        "deleted_at": null,
        "metadata": null,
        "created_at": "2022-06-15T14:30:58.690Z",
        "updated_at": "2022-06-15T14:30:58.690Z"
    }
}
```
3. Login with new user => success
4. Create product -x> Don't possess store_id and there is a message in the server : 
```shell
info:    Processing product.created which has 1 subscribers
warn:    This is an empty method: addDocuments must be overridden by a child class
```
5. What do you mean by "fetch products" ? I don't understand and I'm sorry about that \^\^'

**Comment by shahednasser** [comment]
If the user doesn't have the `store_id` attribute then all steps after will not work. You can try removing from the migrations table the migration `addStoreIdToUser1611063162649` and trying to re-run migrations and see if it adds the store id to the user. I'm not really sure what the issue could be to be honest

**Comment by SullyvanBoulanger** [comment]
Sorry, it don't work \^\^'

I will continue searches in my side, thanks for all your help :)

**Comment by shahednasser** [comment]
I'll label this issue as closed then
