### ISSUE TITLE
User middleware

### ISSUE THREAD

**Issue by adrien2p** [shahednasser/medusa-marketplace-tutorial#2]
It is probably more suitable to store the loggedInUser as part of the container in the middleware. You will dont need to inject the user service and since the services are scoped youll get access to it from the cradle

**Comment by shahednasser** [comment]
I had trouble doing this. Do you mind submitting a pull request with how it should be?

**Comment by adrien2p** [comment]
No problem at all, here it is (#3) 🔥

**Comment by adrien2p** [comment]
I think we can close that issue now 🙌
