### ISSUE TITLE
UserService cannot be overridden.

### ISSUE THREAD

**Issue by yeewaikhaing** [shahednasser/medusa-marketplace-tutorial#21]
Hello, I am a medusa fresher and trying to setup medusa-extender according to this tutorial link(https://medusajs.com/blog/medusa-extender). Although I followed the step-by-step instructions, I got the following error at this step that UserService is overridden. Let me know how can I solve this error. Thanks
<img width="1000" alt="Screen Shot 2565-08-20 at 6 16 31 PM" src="https://user-images.githubusercontent.com/73197238/185745154-6986742c-b4ad-4e16-bbb0-41cd789199fb.png">

**Comment by suitcodemr** [comment]
Yes, I have experienced the same problem.the extended UserService ()

**Comment by suitcodemr** [comment]
Yes, I have experienced the same problem.

The extended UserService as MedusaUserService ("@medusajs/medusa/dist/services") not included the above methods (.validateId_(), .buildQuery_()).

Errors from TypeScript-Linter:
-Property 'validateId_' does not exist on type 'UserService'
-Property 'validateId_' does not exist on type 'UserService'.

I have used the same dependencies and devDependencies from the repository.

I hope someone can help us, too fix this issue. Thanks in advance.

FYI:
StoreService have a similar problem with "withTransaction()"-method and retrieve()-method.

Errors from TypeScript-Linter:
-Property 'retrieve' in type 'StoreService' is not assignable to the same property in base type 'StoreService'
-Type '(relations?: string[]) => Promise<Store>' is not assignable to type '(config?: FindConfig<Store>) => Promise<Store>'

**Comment by Keith-Hon** [comment]
I have the same problem too

**Comment by HarunKilic** [comment]
For `buildQuery_` error, you can use the util instead. 

1. import the util: 
`import { buildQuery } from "@medusajs/medusa/dist/utils/build-query";`

2. Use it:
`const query = buildQuery({ id: userId }, config);`

**Comment by suitcodemr** [comment]
Thanks @HarunKilic it works.
@yeewaikhaing For validateId_() and buildQuery_() you can import the utils from medusajs.
import { buildQuery, validateId } from "@medusajs/medusa/dist/utils";

**Comment by shahednasser** [comment]
Hello everyone, unfortunately, the first parts of the tutorial are currently outdated. You can instead use the full code in this repo.
