### ISSUE TITLE
Tutorial-Step "Create a Store Service to Handle User Insert Events" failed by 'withTransaction' and 'retrieve'

### ISSUE THREAD

**Issue by suitcodemr** [shahednasser/medusa-marketplace-tutorial#23]
Hello, i am a rookie in the medusa-ecosystem and trying to setup medusa-extender according to this tutorial: 
[Create a Marketplace using Medusa: Part 1](https://medusajs.com/blog/medusa-extender)
I got the following errors at this step "Create a Store Service to Handle User Insert Events":

`Property 'withTransaction' in type 'StoreService' is not assignable to the same property in base type 'StoreService'.
  Type '(transactionManager: EntityManager) => StoreService' is not assignable to type '(transactionManager?: EntityManager) => this | StoreService'.
    Type 'StoreService' is not assignable to type 'this | StoreService'.
      Type 'import("[...]/src/modules/store/services/store.service").default' is not assignable to type 'import("[...]/node_modules/@medusajs/medusa/dist/services/store").default'.
        Types of property 'retrieve' are incompatible.
          Type '(relations?: string[]) => Promise<Store>' is not assignable to type '(config?: FindConfig<Store>) => Promise<Store>'.
            Types of parameters 'relations' and 'config' are incompatible.
              Type 'FindConfig<Store>' is missing the following properties from type 'string[]': length, pop, push, concat, and 29 more.ts(2416)`
              
I hope someone can help me/us to solve this problem. Thanks in advance.

**Comment by shahednasser** [comment]
Hi @suitcodemr the tutorial is now outdated. You can instead use the full code in this repo.
