### ISSUE TITLE
How to add new Admin Account ?

### ISSUE THREAD

**Issue by anup-a** [shahednasser/medusa-marketplace-tutorial#5]
Since we have changed the user schema to include store_id, the existing seed data won't work.

This error logs when we try to start server after seeding data (which don't have store_id FK) - 
`
⠼ Initializing database(node:56146) UnhandledPromiseRejectionWarning: QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: temporary_user.store_id
`

So, how should we go about creating multiple admin (vendor) accounts? 

Thanks,

**Comment by anup-a** [comment]
Got a reply from @adrien2p on discord -

I did the following steps - 

1. Remove Not Null Constraint
2. Add store & user through seed data migration and then restart the server.
3. Then update the user in db -> `sqlite3> update user set store_id = "store_01FXW17FX1Y67Q8V027WHF6MNC" where id = "user_adasdasd";`
4. Add the Not null Constraint.

And this worked.

Follow up question, 
How can we have a super admin who can create admin accounts for vendors via admin UI?

**Comment by adrien2p** [comment]
You could create a super role that you attribute to your super admin. Then you should manage the query constraints based on the role. For example the user list should return all users for the super admin. You could then create a rolebased middleware that allow or disallow some features based on the user role.

**Comment by anup-a** [comment]
Thanks, that's what I was planning on doing. 

By the way, does medusa already have an endpoint to register a new user, Let's say can super admin create a store and associate some users as store admin, I didn't see it in docs, so I just have to create a custom endpoint, correct?

**Comment by shahednasser** [comment]
Hi @anup-a that's currently not implemented, so yes you'd have to create it on your own for now.

**Comment by anup-a** [comment]
Thanks
